//go:build integration

package test

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// maxCyclomaticComplexity matches the cyclomatic-complexity ceiling in AFF patterns/governance.json.
const maxCyclomaticComplexity = 9

// minDependencyDiscipline matches the dependency-discipline floor in AFF patterns/governance.json.
const minDependencyDiscipline = 0.8

type baselineReport struct {
	Results []struct {
		File      string `json:"file"`
		Functions []struct {
			Name                 string `json:"name"`
			CyclomaticComplexity int    `json:"cyclomatic_complexity"`
		} `json:"functions"`
		ImportMetrics struct {
			Total  int      `json:"total"`
			Used   int      `json:"used"`
			Unused []string `json:"unused"`
			DDC    float64  `json:"ddc"`
		} `json:"import_metrics"`
	} `json:"results"`
}

func TestGeneratedGoStacksPassFitnessBaseline(t *testing.T) {
	if _, err := exec.LookPath("agent-fitness-functions"); err != nil {
		t.Skip("agent-fitness-functions executable not found on PATH")
	}

	if os.Getenv("MISE_IGNORED_CONFIG_PATHS") == "" {
		if home := os.Getenv("HOME"); home != "" {
			_ = os.Setenv("MISE_IGNORED_CONFIG_PATHS", filepath.Join(home, ".config", "mise", "*")+":"+filepath.Join(home, ".config", "mise", "conf.d", "*"))
		}
	}

	type stackCase struct {
		name        string
		language    string
		projectType string
		stack       string
	}

	stacks := []stackCase{
		{
			name:        "go-cli-cobra",
			language:    "go",
			projectType: "cli",
			stack:       "go-cli-cobra",
		},
		{
			name:        "go-api-chi",
			language:    "go",
			projectType: "api",
			stack:       "go-api-chi",
		},
		{
			name:        "go-web-templ",
			language:    "go",
			projectType: "web",
			stack:       "go-web-templ",
		},
	}

	for _, stack := range stacks {
		t.Run(stack.name, func(t *testing.T) {
			dir := tempRuntimeDir(t)
			envRoot := tempRuntimeDir(t)

			projectType := stack.projectType
			if projectType == "web" {
				projectType = "fullstack"
			}

			runStep(t, "forge init", dir, envRoot, forgeBinary, "init", "--project-name", "Verify "+stack.name, "--language", stack.language, "--project-type", projectType, "--stack", stack.stack, "--author-name", "CI Bot", "--author-email", "ci@example.com", "--remote", "none")

			baselinePath := filepath.Join(envRoot, "baseline.json")
			runStep(t, "agent-fitness-functions baseline", dir, envRoot, "agent-fitness-functions", "baseline", "--repo", dir, "--language", "go", "--output", baselinePath, "--name", "smoke")

			data, err := os.ReadFile(baselinePath)
			if err != nil {
				t.Fatalf("reading baseline report: %v", err)
			}

			var report baselineReport
			if err := json.Unmarshal(data, &report); err != nil {
				t.Fatalf("unmarshaling baseline report: %v", err)
			}

			for _, res := range report.Results {
				// Per Decision D2 in the accepted plan, templ-generated files (*_templ.go) are
				// excluded because their code is machine-generated by the templ compiler.
				if strings.HasSuffix(res.File, "_templ.go") {
					continue
				}

				for _, fn := range res.Functions {
					if fn.CyclomaticComplexity > maxCyclomaticComplexity {
						t.Errorf("%s: function %s cyclomatic complexity = %d (threshold <= %d)", res.File, fn.Name, fn.CyclomaticComplexity, maxCyclomaticComplexity)
					}
				}
				if res.ImportMetrics.Total > 0 && res.ImportMetrics.DDC < minDependencyDiscipline {
					t.Errorf("%s: import dependency discipline = %f (threshold >= %f)", res.File, res.ImportMetrics.DDC, minDependencyDiscipline)
				}
			}
		})
	}
}
